source "https://rubygems.org"

gem "rake", "10.1.0"
gem "sinatra", "1.4.3"
gem "petrovich", "~> 1.0"
gem "sinatra-contrib", "1.4.0"
gem "multi_json", "1.7.7"
gem "sinatra-asset-pipeline", "0.2.0"
gem "evil-front", github: "ai/evil-front"
gem "sprockets-helpers", "1.0.1"
gem "puma"
