source "https://rubygems.org"

gem "sinatra", "1.4.3"
gem "petrovich", "~> 0.1"
gem "sinatra-contrib", "1.4.0"
gem "multi_json", "1.7.7"
gem "sinatra-asset-pipeline", "0.2.0"
gem "evil-front", github: "ai/evil-front"
gem "capistrano", "2.15.5"
gem "unicorn", "4.6.3"
gem "therubyracer", "0.12.0"
gem "sprockets-helpers", "1.0.1"
