# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.6.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-05-08T21:44:01Z"
  labels:
    app: petrovich
  name: petrovich
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - bundle exec puma -t 1:4
    env:
    - name: PATH
      value: /usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: petrovich
    - name: container
      value: podman
    - name: RUBY_VERSION
      value: 2.7.1
    - name: GEM_HOME
      value: /usr/local/bundle
    - name: RACK_ENV
      value: production
    - name: RUBY_DOWNLOAD_SHA256
      value: b224f9844646cc92765df8288a46838511c1cec5b550d8874bd4686a904fcee7
    - name: BUNDLE_SILENCE_ROOT_WARNING
      value: "1"
    - name: BUNDLE_APP_CONFIG
      value: /usr/local/bundle
    - name: LANG
      value: en_US.UTF-8
    - name: RUBY_MAJOR
      value: "2.7"
    image: localhost/petrovich:latest
    name: demo
    ports:
    - containerPort: 9292
      hostPort: 9292
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsUser: 65534
    workingDir: /home/app/petrovich
status: {}

